language: generic
sudo: false
cache:
  directories:
    - /tmp/calibre-installer-cache

env:
  global:
    - PATH=$HOME/calibre:$HOME/bin:$PATH
    - GEN_EPUB_BOOK_VERSION=v0.1.0

before_install:
  - openssl aes-256-cbc -K $encrypted_081938a76f01_key -iv $encrypted_081938a76f01_iv -in gh_rsa.enc -out gh_rsa -d

install:
  - curl -SL https://download.calibre-ebook.com/linux-installer.py | python -c "import sys; import os; main=lambda x:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main(os.getenv('HOME'))"
  - ebook-convert --version
  -
  - mkdir -p "$HOME/bin"
  - curl -SL "https://github.com/nabijaczleweli/gen-epub-book.cpp/releases/download/$GEN_EPUB_BOOK_VERSION/gen-epub-book-$GEN_EPUB_BOOK_VERSION" -o "$HOME/bin/gen-epub-book"

before_script:
  - (
      if ! [[ "$TRAVIS_COMMIT_RANGE" == "" ]]; then
        echo "Update kaschism for commits $TRAVIS_COMMIT_RANGE";
        echo;
        git log "$TRAVIS_COMMIT_RANGE" --pretty=oneline 2>/dev/null || :;
      else
        echo "Update kaschism for commit $TRAVIS_COMMIT";
        echo;
        echo "$TRAVIS_COMMIT_MESSAGE";
      fi;
    ) > $TRAVIS_BUILD_DIR/../DOC_UPDATE_MSG
  - mkdir -p ~/.ssh && cp gh_rsa ~/.ssh/id_rsa && chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
  - git clone -b master "git@github.com:nabijaczleweli/nabijaczleweli.github.io.git" "$TRAVIS_BUILD_DIR-webpage"
  - mkdir -p "$TRAVIS_BUILD_DIR-webpage/kaschism"

script:
  - make OUTDIR="../kaschism-webpage/kaschism/"

after_success:
  - pushd "$TRAVIS_BUILD_DIR-webpage/"
  - git config --global user.email "nabijaczleweli@gmail.com"
  - git config --global user.name "Nabijaczleweli Autouploader Bot"
  - git config --global push.default simple
  - git add .
  - git commit -F ../DOC_UPDATE_MSG
  - git push
  - popd
